### ISSUE TITLE
Using appmetrics-dash with existing socket.io connection

### ISSUE THREAD

**Issue by Kristina-Ribacionkaite** [RuntimeTools/appmetrics-dash#109]
Passing server to monitor options results in `Error during websocket handshake: Unexpected response code: 400`. Without server option socket.io client and backend connects fine, but it creates new http server with default port 3001. 
Is there a way to keep existing socket.io connection without creating a new server? 
We are using node 6, express ^4 and socket.io and socket.io-client 1.7.3.

**Comment by tobespc** [comment]
@Kristina-Ribacionkaite How are you passing the server options ?

You should be able to just put the following in your code to use the existing server

var dash = require('appmetrics-dash');
dash.attach();

Make sure you add this before you require any servers

**Comment by Kristina-Ribacionkaite** [comment]
@tobespc we are using _dash.monitor()_

```
const appm = require('appmetrics');
const dash = require('appmetrics-dash');

dash.monitor({ server: ourAwesomeServer, appmetrics: appm });
```

Where _ourAwesomeServer_ is our http server.

**Comment by tobespc** [comment]
@Kristina-Ribacionkaite   ok, can you replace those three lines with these 2 please

var dash = require('appmetrics-dash');
dash.attach();

make sure your put those lines before you define your ourAwesomeServer

**Comment by noxxious** [comment]
Hi, the problem here is actually that appmetrics-dash will use the default socket.io listening path (/socket.io), which is wrong as most of the client applications due that. The proper way would be listen to a different (appmetrics-dash specific path). I've created the PR #136

**Comment by mrausch** [comment]
+1 for accepting PR #136
I have an application that already uses socket.io and I cannot use appmetrics-dash with that application.
