### ISSUE TITLE
HTTP Summary box has scrollbars even though there is screen space below

### ISSUE THREAD

**Issue by sjanuary** [RuntimeTools/appmetrics-dash#129]
![summary](https://user-images.githubusercontent.com/14993288/33553318-258965f2-d8f0-11e7-9c1c-d69e1ba13813.PNG)

**Comment by sjanuary** [comment]
All the vertical space should be used before adding scrollbars

**Comment by robbinspg** [comment]
Not sure I agree. The frame lines up with the others.

**Comment by sjanuary** [comment]
The others could also fill the space and have 50% of the height each

**Comment by jamesemwallis** [comment]
I've made some mockups of two designs.

After speaking with Sian, Julie and Toby we've decided to go with the second design as its easier on the eye and utilises all the screen for http summary box.

![screen shot 2017-12-05 at 10 55 17](https://user-images.githubusercontent.com/17385115/33604673-bafcc264-d9ae-11e7-912c-d0770c273969.png)
![screen shot 2017-12-05 at 11 18 20](https://user-images.githubusercontent.com/17385115/33604677-bc9ece46-d9ae-11e7-8518-616632dc4174.png)

**Comment by robbinspg** [comment]
The top one is better imo

**Comment by sjanuary** [comment]
Fixed by #130
