### ISSUE TITLE
Have a README

### ISSUE THREAD

**Issue by sam-github** [RuntimeTools/appmetrics-dash#13]
master has a README, https://github.com/RuntimeTools/appmetrics-dash/blob/b2d1070393d091996e4f104864a144ef5fd663ce/README.md, which is OK, but it got lost in the rewrite.

I added a bit of an update to the README in #11, with API info. Once it lands, though, it will still need a bit more usage info to be useful to people using the dashboard directly.

**Comment by NikCanvin** [comment]
sure thing Sam, we plan to fully update it within next few weeks

**Comment by tobespc** [comment]
needs a complete rewrite, will be done next week

**Comment by mattcolegate** [comment]
README needs review by @sam-github , @NikCanvin and @tobespc before issue can be closed.
