### ISSUE TITLE
passing in `options.url` to monitor causes dashboard not to show metrics

### ISSUE THREAD

**Issue by mannypamintuan** [RuntimeTools/appmetrics-dash#160]
**Issue**:
Passing in a `HTTP` server object via `options.server` and a non-default url via `options.url` is causing the metrics dashboard to be empty.

----------------
using hapi v16
```javascript
const dash = require('appmetrics-dash');
...
dash.monitor({
    server: server.select('web').listener,
    url: '/new/appdash'
});
```
![screen shot 2018-08-29 at 1 55 00 pm](https://user-images.githubusercontent.com/5340430/44809113-7d910b80-ab93-11e8-84be-88e2f0d0dd1d.png)

----------------
**Context:**
there are multiple connections for this node.js app so using `server.select('web').listener` returns the `HTTP` server object for the `web` connection.
https://github.com/hapijs/hapi/blob/v16/API.md#serverlistener

-----------------

Could it be because:
```
io = require('socket.io')(server, { path: '/appmetrics-dash/socket.io' });
```
https://github.com/RuntimeTools/appmetrics-dash/blob/master/lib/appmetrics-dash.js#L171

And instead if `options.url` exists, setting the `path` to `${options.url}/socket.io`?

**Comment by s-h-a-d-o-w** [comment]
This is the more important problem (see also my PR):
https://github.com/RuntimeTools/appmetrics-dash/blob/master/public/index.html#L32

**Comment by tobespc** [comment]
@s-h-a-d-o-w  @mannypamintuan Sorry for not having responded sooner to this, will pick this up tomorrow in the office and get back on top of the outstanding issues and PR's
