### ISSUE TITLE
Monitor options constructor

### ISSUE THREAD

**Issue by gustavomassa** [RuntimeTools/appmetrics-dash#166]
Hello,

The monitor options constructor is not working very well.
When passing both url and server parameters, the dashboard does not load the data.

![image](https://user-images.githubusercontent.com/16235598/47476922-05447080-d7f9-11e8-8018-0cf28c8a2070.png)
![image](https://user-images.githubusercontent.com/16235598/47477077-d24eac80-d7f9-11e8-9ff5-1b94ae1d7bba.png)

```
const monitorDashboard = require('appmetrics-dash');
//passing just the server option works fine
monitorDashboard.monitor({ server: ServerController.Instance.$httpsServer });
//passing url and server does not work
//monitorDashboard.monitor({ title: `Monaco Monitor Dashboard - Worker ${cluster.worker.id}`, url: `/monitor/${cluster.worker.id}`, server: ServerController.Instance.$httpsServer });
```

Also, I think the appmetrics constructor options are missing, I would like to pass those options to appmetrics-dash:
```
this.appmetrics = require('appmetrics');
        this.appmetrics.configure(
            {
                applicationID: WBA.config().name,
                mqtt: 'off',
                profiling: 'off'
            }
        );
this.monitoring = this.appmetrics.monitor();
```
I've tried passing the appmetrics object instance to the appmetrics-dash options, but it does not work.

Thanks

**Comment by sjanuary** [comment]
@gustavomassa I think the URL issue could be fixed by https://github.com/RuntimeTools/appmetrics-dash/pull/163

The empty dashboard you're seeing tells us that the socket connection isn't working.

**Comment by gustavomassa** [comment]
@sjanuary thank you for letting me know, I will test and let you know.

**Comment by gustavomassa** [comment]
@sjanuary The appmetrics dash is not even loading anymore, I'm not able to access it anymore using my server with the default route(appmetrics-dash) or using a custom route (monitor). It seems that the server property is not working anymore.

```
    private initAppMetrics(): void {
        try {
            this.appmetrics = require('appmetrics');
            this.appmetrics.configure(
                {
                    applicationID: config.name,
                    mqtt: 'off',
                    profiling: 'off'
                }
            );
            //this.monitoring = this.appmetrics.monitor();
            this.dashboard = require('appmetrics-dash');
            this.dashboard.monitor({ appmetrics: this.appmetrics, server: ServerController.Instance.$httpsServer, title: 'Monaco Monitor Dashboard', url: '/monitor' });

        } catch (ex) {
            Webbuffet.logError(new Error(ex));
        }
    }
```
