### ISSUE TITLE
Dashboard is hanging after around 10 minutes of monitoring acme-air

### ISSUE THREAD

**Issue by tobespc** [RuntimeTools/appmetrics-dash#19]
running in chrome, localhost:3000/appmetrics-dash became unresponsive after around 10 minutes of acmeair running under load

**Comment by mattcolegate** [comment]
Found a bug in gcChart - incorrect variable name was sending the data point limitation routine into an infinite loop. Fixed and tested - appmetrics-dash has been running for 25 minutes on full acme-air with no crash.

**Comment by JulienArnold** [comment]
Was going to check in the same thing but Matt beat me to it :-) Similar results produced here, started driver run at ~12:51 and it's currently 13:11 and still going without crash
