### ISSUE TITLE
appmetrics-dash does not start

### ISSUE THREAD

**Issue by PranjalGuptaSwaniti** [RuntimeTools/appmetrics-dash#190]
Hey,
May be I am newbie into this but, I followed the guide to set-up appmetrics-dash as defined on the github. And, I am running into 2 problems
1. The Metrics Dashboard does not open at localhost:3001/appmetrics-dash . I get this in browser window.
`Cannot GET /appmetrics-dash`
2. The PORT I had used for my nodejs app gets busy. When I restart the app.
```
com.ibm.diagnostics.healthcenter.loader INFO: Node Application Metrics 5.1.1.202005081919 (Agent Core 4.0.5)
[Fri May  8 20:09:21 2020] com.ibm.diagnostics.healthcenter.mqtt INFO: Connecting to broker localhost:1883
appmetrics-dash listening on :::3001
Port 7878 is already in use
```

I am using Nodemon to start the app and have defined - 
require('appmetrics-dash').attach();
appdash = require('appmetrics-dash').monitor();
In the server.js - the start file

**Comment by mattcolegate** [comment]
Hi @PranjalGuptaSwaniti,

It looks like you're trying to start appmetrics-dash twice - which statement you use depends on your Node.js application.
* If your application already creates one or more HTTP servers and you want to attach appmetrics-dash to all of them, just use `require('appmetrics-dash').attach();`. This will start appmetrics-dash on all of your created HTTP servers and it will be available at `<yourServerHostName>:<yourServerPortNumber>/appmetrics-dash`
* If your application creates no HTTP servers then just use `require('appmetrics-dash').monitor();`. Appmetrics-dash will create it's own HTTP server and start hosting on localhost:3001/appmetrics-dash. You can change the hostname, port and/or endpoint by supplying options to the monitor() function.

**Comment by PranjalGuptaSwaniti** [comment]
Ohh!! Waow, this was great and to the point. My Application had already created HTTP server and I had to attach app-metrics to same. Thank you @mattcolegate for your prompt response on this.

**Comment by mattcolegate** [comment]
Glad I could help @PranjalGuptaSwaniti - if this has fixed your problem, would you close this issue please?

**Comment by PranjalGuptaSwaniti** [comment]
Yes, sure!!
