### ISSUE TITLE
Express integration

### ISSUE THREAD

**Issue by ysilvela** [RuntimeTools/appmetrics-dash#2]
How can integrate with express?
My code is:

app = express(); 
app.listen(self.port, self.ipaddress, function() {
            console.log('%s: Node server started on %s:%d ...',  Date(Date.now() ), self.ipaddress, self.port);
 });       

Thanks,
Regards

**Comment by tobespc** [comment]
Hi,

To use appmetrics-dash with express, add the following before your app=express(); line

var appdash = require('appmetrics-dash').start();

**Comment by lanespade** [comment]
Hi,

I am having a similar issue, I currently have...

`
require('appmetrics').monitor()
require('appmetrics-dash').start()

var app = require('express')()
app.listen(8080)
`

...in my server.js file and everything starts up correctly, but none of my routes work nor do the app metrics dashboard routes (localhost:3000/admin). I have tried passing an object like...

`
var config = {
    "server": "localhost"
}
`

...with http:// and https:// pre-pended and 127.0.0.1 and I also tried setting the port on the config to be the same as my service (8080), but nothing seems to work. Any tips?

**Comment by lanespade** [comment]
I also tried removing appmetrics from my package.json along with the `require('appmetrics').monitor()` line, but still, none of my endpoint work.

**Comment by tobespc** [comment]
Can you try this please?  This is my testcase I use

#######
// This application uses express as its web server
// for more info, see: http://expressjs.com
var express = require('express');

var dash = require('appmetrics-dash').monitor();

// cfenv provides access to your Cloud Foundry environment
// for more info, see: https://www.npmjs.com/package/cfenv
var cfenv = require('cfenv');

// create a new express server
var app = express();

// serve the files out of ./public as our main files
app.use(express.static(__dirname + '/public'));

// get the app environment from Cloud Foundry
var appEnv = cfenv.getAppEnv();

// start server on the specified port and binding host
var server = app.listen(appEnv.port, '0.0.0.0', function() {
	// print a message when the server starts listening
  console.log("server starting on " + appEnv.url);
});
#########

**Comment by tobespc** [comment]
@lanespade is this still an issue or can we close this off now ?

**Comment by lane-flexe** [comment]
@tobespc sorry about not responding recently, I eventually did get it to work using only `appmetrics-dash` as the dependency, version `1.0.x`. My setup looks like...

```
// Imports, ports, etc.

// Only attach metrics dashboard once (fix for hot reloading during development)
if(!module.parent) {
	// Start metrics dashboard before requiring express
	// https://github.com/RuntimeTools/appmetrics-dash/issues/2#issuecomment-215314799
	require('appmetrics-dash').start({ port: metricsPort })
}

const app = express()

// Use bindings

// Only listen once (fix for hot reloading during development)
if(!module.parent) {
	app.listen(servicePort)
	console.log('Running on http://localhost:' + servicePort)
}
``` 
...so, yes, this is not longer an issue for me and can be closed.

**Comment by tobespc** [comment]
@lanespade Thats great news, glad you got it up and running
