### ISSUE TITLE
appmetric-dash not responsive when under stress

### ISSUE THREAD

**Issue by smartmouse** [RuntimeTools/appmetrics-dash#28]
when we keep sending http requests. the appmetrics dash boars is not responsible.

It will be useful to take/capture snap shots of the data in dashboard especially  when the application is under stress.

<img width="1272" alt="screen shot 2017-02-28 at 5 14 14 am" src="https://cloud.githubusercontent.com/assets/4519627/23401388/83ffddfc-fd75-11e6-85ee-66dfc99baba4.png">

**Comment by tobespc** [comment]
@smartmouse When did you update the dashboard ?  We've put a load of changes in to fix the performance when too much data comes across

**Comment by tobespc** [comment]
We are not seeing this at all with the latest builds. closing as unrecreatable

**Comment by smartmouse** [comment]
whatever version apiconnect pull in 
"_args": [
    [
      {
        "raw": "appmetrics-dash@^3.0.0-RC.1",
        "scope": null,
        "escapedName": "appmetrics-dash",
        "name": "appmetrics-dash",
        "rawSpec": "^3.0.0-RC.1",
        "spec": ">=3.0.0-RC.1 <4.0.0",
        "type": "range"
      },
