### ISSUE TITLE
"No Data Available" doesn't move on resize

### ISSUE THREAD

**Issue by mattcolegate** [RuntimeTools/appmetrics-dash#30]
HTTP Throughput Chart and HTTP Outbound Requests display "No Data Available" when no data is available. When resizing the graphs, the "No Data Available" statement doesn't move to the center of the graph - this can lead to truncation, easily seen when HTTP Throughput is resized.
![35413bc2f7bf3e46](https://cloud.githubusercontent.com/assets/15730986/23466454/16cb847e-fe93-11e6-96f3-46d729ee7ca4.jpg)

**Comment by robbinspg** [comment]
I believe this was fixed in the graphmetrics package
