### ISSUE TITLE
The charts data squashed up  and not flexible enough to adjust each chart size

### ISSUE THREAD

**Issue by smartmouse** [RuntimeTools/appmetrics-dash#34]
For the full screen , has has 5 charts on a row, but some data are squashed,
the only way is to re-size down to one chart per row, there is no flexible to re-size each chart or
the choice to make 3 charts per row.

**5 charts on one row**
<img width="1276" alt="screen shot 2017-03-03 at 3 21 58 pm" src="https://cloud.githubusercontent.com/assets/4519627/23567737/b9b714b2-0025-11e7-97f8-a0d15e1db811.png">

one chart per row
<img width="702" alt="screen shot 2017-03-03 at 2 34 13 pm" src="https://cloud.githubusercontent.com/assets/4519627/23567761/dac7f8c4-0025-11e7-9eef-20e3cc630e31.png">

**Comment by tobespc** [comment]
Adding the ability to resize individual charts is a future enhancement

**Comment by sjanuary** [comment]
We can't resize individual charts at the moment but we've added the ability to maximize every chart and view it fullscreen, which I think fulfils this requirement.
