### ISSUE TITLE
The environment chart is waste of space

### ISSUE THREAD

**Issue by smartmouse** [RuntimeTools/appmetrics-dash#35]
There is no need for environment chart -- what information you need to display beside os, etc...
You can display them in the title of in the show node report.
Then you can free up some space for the other chart area.

<img width="1276" alt="screen shot 2017-03-03 at 3 21 58 pm" src="https://cloud.githubusercontent.com/assets/4519627/23567833/25f54dd8-0026-11e7-886f-bb187b5a6a97.png">

**Comment by tobespc** [comment]
The environment panel is useful but we have not finalised the content or final size
