### ISSUE TITLE
Should have a LICENSE file

### ISSUE THREAD

**Issue by rmg** [RuntimeTools/appmetrics-dash#36]
It is customary for there to be a `LICENSE` file in the root of the repo. In addition to it being common convention, GitHub and other repo scanning tools look for it.

The license is mentioned in `package.json`, `README.md`, and in all the js files in the copyright notices. so it's completely clear that this package is released under an Apache 2.0 license and it shouldn't be a big deal to add.

**Comment by tobespc** [comment]
I agree, this will be added by the time we release the next version
