### ISSUE TITLE
Generate Node Report is broken

### ISSUE THREAD

**Issue by cfjedimaster** [RuntimeTools/appmetrics-dash#67]
I've got a button that says, "Generate Node Report", but on click I'm told: 

node reporting not available

The dashboard should recognize this and disable the button (and also tell me how to enable it - I honestly have no idea what it is and why it isn't working).

**Comment by sam-github** [comment]
duplicate of https://github.com/RuntimeTools/appmetrics-dash/issues/26 (and I agree the button should be disabled).

It means you don't have a compiler toolchain, btw, your `npm install` should have spewed some warnings to the effect that the optional node-report dependency failed to build.

**Comment by tobespc** [comment]
@cfjedimaster we are working on improving the UX this should the feature be unavailable
