### ISSUE TITLE
Documentation confusion

### ISSUE THREAD

**Issue by cfjedimaster** [RuntimeTools/appmetrics-dash#68]
The link to the docs in the Dashboard goes to the App Metrics docs, but not the docs on working with the dashboard. I know docs must exist - for example, I know you can tell the dashboard to attach to the current server and *not* fire up it's own server. But where is that documented? 

In general, I get this Dashboard is a UI on top of App Metrics, but there really needs to be a set of docs for the dashboard *as well as* some guidance in terms of how I'd use the docs in App Metrics along with this tool.

For example, if I remember right, in App Metrics I had to turn on support for Mongo. Apparently, the Dashboard stuff does this for me automatically. So given that the dashboard is using some app metric settings, we need docs on that as well.

Let me know if this doesn't make sense.

**Comment by cfjedimaster** [comment]
Related, and this may be a new ticket, but the README documentation link here (https://developer.ibm.com/node/monitoring-post-mortem/application-metrics-node-js/) also goes to App Metrics docs, and not docs for the dashboard. It should go here: https://github.com/RuntimeTools/appmetrics-dash/blob/master/README.md

**Comment by cfjedimaster** [comment]
In fact, I'd say most of my issue is that the docs don't lead to *this* REPO. That would fix it all probably.

**Comment by tobespc** [comment]
@cfjedimaster Thanks for the feedback, I'll get the links and docs all reviewed and updated today

**Comment by sjanuary** [comment]
"Readme" link now updated on https://developer.ibm.com/node/monitoring-post-mortem/application-metrics-node-js/
