### ISSUE TITLE
Looking for Contributors?

### ISSUE THREAD

**Issue by william-taylor** [RuntimeTools/appmetrics-dash#76]
Hi,

I was wondering if this project is looking for contributors? Started using it recently and would love to contribute in a few ways. Would like to look at dashboard themes, more environment info in the dashboard as well as looking at solving issues posted recently by various users.

Are these sort of contributions welcome?

Thanks

**Comment by sjanuary** [comment]
Yes, we welcome contributions. Please see https://github.com/RuntimeTools/appmetrics-dash/blob/master/CONTRIBUTING.md for details about the contributor licence agreement and other information.  If you want to do anything more involved than a bug fix or a minor enhancement then we would recommend discussing it in an issue first before doing the work to make sure that it's likely to be accepted.  We're also keen to improve test coverage and may not accept new code unless there are accompanying tests.

**Comment by tobespc** [comment]
@william-taylor as I see you are now contributing I'm going to close this issue.
