### ISSUE TITLE
Support for Node v8

### ISSUE THREAD

**Issue by cfjedimaster** [RuntimeTools/appmetrics-dash#79]
I know it's been out for like mere minutes, but it looks like you can't install with Node v8.

**Comment by sam-github** [comment]
This is a package bug: when appmetrics 3.x was release, the dependency spec in appmetrics-dash should have been bumped to `^3`, but it wasn't. appmetrics 3.x supports 8.x

**Comment by cfjedimaster** [comment]
Cool - quick fix then? :)

**Comment by cfjedimaster** [comment]
I'm still seeing this an issue. I removed appmetrics-dash from my app, added it back, and it still fails w/ the same error.

**Comment by sam-github** [comment]
The fix wasn't released, just merged to master.

**Comment by cfjedimaster** [comment]
Gotcha - will be patient. :)

**Comment by tobespc** [comment]
@sam-github @cfjedimaster Will look to get this released asap
