### ISSUE TITLE
Remove redundant admin pwd code

### ISSUE THREAD

**Issue by NikCanvin** [RuntimeTools/appmetrics-dash#8]
When we merged the old dash with the new dash, we picked up Admin Pwd code that needs to be removed.

**Comment by sam-github** [comment]
It wasn't clear to my if the authentication should be removed, or be optional.

And if optional, if it should default to be off or on.

#11 leaves authentication in, makes it default to on (with user/pass of "admin:admin") as it was before, but makes it possible to opt-out, or provide your own user/passwords

**Comment by koliapp2019** [comment]
So how do we password protect the dashboard URL?

**Comment by mattcolegate** [comment]
By either attaching/monitoring a server that already has that security middleware enabled, or by passing in the security middleware using `options.middleware` to an attach or monitor call.
