### ISSUE TITLE
Heap Snapshot UI Improvement

### ISSUE THREAD

**Issue by william-taylor** [RuntimeTools/appmetrics-dash#81]
The heap snapshot feature is really handy. However the UI for it seems a bit plain. Would it be worth while for me to submit a pull request with the following changes?

* Replace file link text in the modal with a 'Download' button that downloads it to the default location
* Make the filename include the date and time it was created so multiple reports are distinguishable
* Add an 'Open' button that opens the contents of the file in a new tab

**Comment by tobespc** [comment]
@william-taylor Hi, that is a great idea,  please go ahead and submit the pull request.  However, before we can accept it you will need to read and confirm the contribution guidelines  

https://github.com/RuntimeTools/appmetrics-dash/blob/master/CONTRIBUTING.md

**Comment by sjanuary** [comment]
Still happy to accept a PR for this, but I'm going to close this issue as the question has been answered.
